services:
  personal-website-db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: personal_website
      POSTGRES_USER: django
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
  
  personal-website-django:
    depends_on:
      - personal-website-db
    build: 
      context: ./website
      dockerfile: Dockerfile.prod
    command: gunicorn website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/website/staticfiles
    expose:
      - 8000
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      SECRET_KEY: /run/secrets/secret_key
      DB_PASSWORD: /run/secrets/db_password
      DEBUG: 0
      ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
    secrets:
      - secret_key
      - db_password
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/website/staticfiles
    ports:
      - 80:80
    depends_on:
      - personal-website-django

secrets:
  secret_key:
    file: secrets/secret_key.txt
  db_password:
    file: secrets/db_password.txt

volumes:
  db_data:
  static_volume: